### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by hamidzr** [brollb/dev-updater#1]
```
1|dev-updater       | TypeError: Cannot read property 'replace' of undefined
1|dev-updater       |     at /home/ubuntu/dev-updater/app.js:33:30
1|dev-updater       |     at Layer.handle [as handle_request] (/home/ubuntu/dev-updater/node_modules/express/lib/router/layer.js:95:5)
1|dev-updater       |     at next (/home/ubuntu/dev-updater/node_modules/express/lib/router/route.js:131:13)
1|dev-updater       |     at Route.dispatch (/home/ubuntu/dev-updater/node_modules/express/lib/router/route.js:112:3)
1|dev-updater       |     at Layer.handle [as handle_request] (/home/ubuntu/dev-updater/node_modules/express/lib/router/layer.js:95:5)
1|dev-updater       |     at /home/ubuntu/dev-updater/node_modules/express/lib/router/index.js:277:22
1|dev-updater       |     at Function.process_params (/home/ubuntu/dev-updater/node_modules/express/lib/router/index.js:330:12)
1|dev-updater       |     at next (/home/ubuntu/dev-updater/node_modules/express/lib/router/index.js:271:10)
1|dev-updater       |     at /home/ubuntu/dev-updater/node_modules/body-parser/lib/read.js:129:5
1|dev-updater       |     at invokeCallback (/home/ubuntu/dev-updater/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
```

**Comment by umesh-timalsina** [comment]
This is happening whenever a `ping` i.e `req.header['x-github-event']` is `ping` event is sent from github. In that case, the payload doesn't have `ref`.
